/**
 * src/domain/planning.js
 *
 * Planning domain logic, ported from scripts/planejar.mjs (CLI) for the browser.
 * No Node dependencies (fs, path, readline, etc.).
 *
 * Main exports:
 *   buildCourseGraph(ppcJson)               -> { nodes, prereqs, coreqs, suggestedSemester }
 *   buildOfferIndex(offerJson, turno)           -> Map<codigo, { codigo, periodo, nome, carga_horaria, turmas }>
 *   inferNextSemester(rows, anoInicio)           -> { courseTerm, ano, offerTerm }
 *   generateSemester(params)                        -> { newRows, courseTerm, ano, offerTerm }
 *   enrichRowsWithOffer(rows, s1, s2, turno)    -> PlanningRow[]  (fills turma horarios from offer)
 *   upsertSemester(rows, sc, newRows)            -> PlanningRow[]
 *   groupUnique(rows)                            -> PlanningRow[]
 */

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function normalizeCourseId(id) {
  const trimmed = String(id ?? "").trim();
  const m = trimmed.match(/^\d+\.([A-Z]{2,}\d{3,})$/);
  if (m) return m[1];
  return trimmed;
}

function hhmmToMinutes(hhmm) {
  const m = String(hhmm ?? "")
    .trim()
    .match(/^(\d{1,2}):(\d{2})$/);
  if (!m) return null;
  const hh = Number(m[1]);
  const mm = Number(m[2]);
  if (!Number.isFinite(hh) || !Number.isFinite(mm)) return null;
  if (hh < 0 || hh > 23 || mm < 0 || mm > 59) return null;
  return hh * 60 + mm;
}

function sectionMatchesShift(turma, turno) {
  if (turno === "dia") return true;

  const slots = Array.isArray(turma?.horarios) ? turma.horarios : [];
  if (slots.length === 0) return true;

  const CUTOFF = 13 * 60; // 13:00

  if (turno === "manha") {
    return slots.some((h) => {
      const min = hhmmToMinutes(String(h?.inicio ?? "").trim());
      return min !== null && min < CUTOFF;
    });
  }
  if (turno === "tarde") {
    return slots.some((h) => {
      const min = hhmmToMinutes(String(h?.inicio ?? "").trim());
      return min !== null && min >= CUTOFF;
    });
  }
  return true;
}

function normalizeSectionsFromOffer(disciplina, turno = "dia") {
  const turmas = Array.isArray(disciplina?.turmas) ? disciplina.turmas : [];
  const filtered =
    turno === "dia"
      ? turmas
      : turmas.filter((t) => sectionMatchesShift(t, turno));

  return filtered.map((t) => ({
    codigo: String(t?.turma ?? t?.codigo ?? "").trim(),
    horarios: Array.isArray(t?.horarios)
      ? t.horarios
          .map((h) => ({
            dia: String(h?.dia ?? "").trim(),
            inicio: String(h?.inicio ?? "").trim(),
            fim: String(h?.fim ?? "").trim(),
          }))
          .filter((h) => h.dia && h.inicio && h.fim)
      : [],
    docente: String(t?.docente ?? "").trim(),
  }));
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

/**
 * Builds the PPC graph from the JSON generated by processar-ppc.mjs.
 *
 * @param {object} ppcJson
 * @returns {{ nodes: Map, prereqs: Map, coreqs: Map, suggestedSemester: Map }}
 */
export function buildCourseGraph(ppcJson) {
  const nodes = new Map(); // codigo -> { codigo, nome }
  const prereqs = new Map(); // codigo -> Set<string>
  const coreqs = new Map(); // codigo -> Set<string>
  const suggestedSemester = new Map(); // codigo -> number

  const courses = ppcJson?.courses ?? {};
  for (const [k, v] of Object.entries(courses)) {
    const code = normalizeCourseId(v?.code ?? k);
    if (!code) continue;

    nodes.set(code, { codigo: code, nome: String(v?.name ?? "").trim() });
    prereqs.set(
      code,
      new Set((v?.prereq ?? []).map(normalizeCourseId).filter(Boolean)),
    );
    coreqs.set(
      code,
      new Set((v?.coreq ?? []).map(normalizeCourseId).filter(Boolean)),
    );

    const s = v?.suggestedSemester;
    if (Number.isFinite(s) && s > 0) suggestedSemester.set(code, Math.floor(s));
  }

  for (const c of nodes.keys()) {
    if (!prereqs.has(c)) prereqs.set(c, new Set());
    if (!coreqs.has(c)) coreqs.set(c, new Set());
  }

  return { nodes, prereqs, coreqs, suggestedSemester };
}

/**
 * Builds an offer index keyed by discipline code.
 *
 * @param {object} offerJson  - JSON generated by processar-oferta.mjs
 * @param {"dia"|"manha"|"tarde"} turno
 * @returns {Map<string, object>}
 */
export function buildOfferIndex(offerJson, turno = "dia", filterTurno = false) {
  const byCode = new Map();
  const disciplinas = Array.isArray(offerJson?.disciplinas)
    ? offerJson.disciplinas
    : [];

  for (const d of disciplinas) {
    const codigo = String(d?.codigo ?? "").trim();
    if (!codigo) continue;

    byCode.set(codigo, {
      codigo,
      periodo: String(d?.periodo ?? "").trim(),
      nome: String(d?.nome ?? "").trim(),
      carga_horaria: d?.carga_horaria != null ? String(d.carga_horaria) : "",
      turmas: normalizeSectionsFromOffer(d, filterTurno ? turno : "dia"),
    });
  }

  return byCode;
}

/**
 * Infers the next course semester and the (ano, offerTerm) pair from
 * existing planning rows.
 *
 * Alternation rule:
 *   sc=1 -> anoInicio/entryTerm
 *   sc=2 -> anoInicio/(3-entryTerm)
 *   sc=3 -> (anoInicio+1)/entryTerm
 *   ...
 *
 * @param {any[]} rows              - existing planning rows
 * @param {number} anoInicio        - base year, default 2024
 * @param {number} scInicio         - starting course semester, default 1
 * @param {number} entryTerm - offer semester for the first course semester (1 or 2, default 1)
 * @returns {{ courseTerm: number, ano: number, offerTerm: number }}
 */
export function inferNextSemester(
  rows,
  anoInicio = 2024,
  scInicio = 1,
  entryTerm = 1,
) {
  const nonDispensa = (Array.isArray(rows) ? rows : []).filter(
    (r) => String(r?.semestre_curso ?? "").trim() !== "_",
  );

  let maxSc = null;
  for (const r of nonDispensa) {
    const sc = Number(r.semestre_curso);
    if (!Number.isFinite(sc) || sc <= 0) continue;
    if (maxSc === null || sc > maxSc) maxSc = sc;
  }

  const courseTerm = maxSc === null ? scInicio : maxSc + 1;

  // The offer semester alternates from entryTerm.
  // If entryTerm=1: sc1->1, sc2->2, sc3->1, ...
  // If entryTerm=2: sc1->2, sc2->1, sc3->2, ...
  const offset = courseTerm - scInicio; // steps since the start
  const offerTerm = ((entryTerm - 1 + offset) % 2) + 1;

  // The year advances every 2 course semesters from anoInicio.
  // When entryTerm=1: sc1=anoInicio/1, sc2=anoInicio/2, sc3=anoInicio+1/1 ...
  // When entryTerm=2: sc1=anoInicio/2, sc2=anoInicio+1/1, sc3=anoInicio+1/2 ...
  const totalTermsElapsed = offset; // 0-based
  const entryTermOffset = entryTerm - 1; // 0 or 1
  const ano = anoInicio + Math.floor((entryTermOffset + totalTermsElapsed) / 2);

  return { courseTerm, ano, offerTerm };
}

/**
 * Generates the rows for the next course semester based on the PPC, offer, and existing planning.
 *
 * @param {{
 *   rows: any[],
 *   ppcJson: object,
 *   offerJson: object | null,
 *   turno: "dia"|"manha"|"tarde",
 *   semOferta: boolean,
 *   anoInicio?: number,
 *   scInicio?: number,
 *   entryTerm?: number,
 *   strictCoreq?: boolean,
 * }} params
 *
 * @returns {{ newRows: any[], courseTerm: number, ano: number, offerTerm: number }}
 */
export function generateSemester({
  rows,
  ppcJson,
  offerJson,
  turno,
  semOferta,
  anoInicio = 2024,
  scInicio = 1,
  entryTerm = 1,
  strictCoreq = true,
}) {
  const { courseTerm, ano, offerTerm } = inferNextSemester(
    rows,
    anoInicio,
    scInicio,
    entryTerm,
  );

  const { nodes, prereqs, coreqs, suggestedSemester } =
    buildCourseGraph(ppcJson);

  const offerByCode = semOferta
    ? new Map()
    : buildOfferIndex(offerJson ?? {}, turno);

  // Auxiliary sets
  const completed = buildCompletedSet(rows, courseTerm);
  const alreadyPlanned = buildAlreadyPlannedSet(rows);

  // Courses already in this semester in the planning (seed)
  const existingThisSemester = rowsForTerm(rows, courseTerm);
  const seedCodes = existingThisSemester.map((r) => r.codigo);

  // Candidates sorted by suggested semester in the PPC
  const isDisciplinaCodigo = (c) =>
    /^[A-Z]{2,}\d{3,}$/.test(String(c ?? "").trim());

  const sortBySuggested = (a, b) => {
    const sa = suggestedSemester.get(a) ?? 9999;
    const sb = suggestedSemester.get(b) ?? 9999;
    if (sa !== sb) return sa - sb;
    return String(a).localeCompare(String(b));
  };

  const offeredCodes = semOferta
    ? Array.from(nodes.keys()).filter(isDisciplinaCodigo).sort(sortBySuggested)
    : Array.from(offerByCode.keys())
        .filter((c) => nodes.has(c))
        .sort(sortBySuggested);

  // Seleção
  const selected = [];
  const selectedSet = new Set();

  const missingPrereqs = (codigo) => {
    const reqs = prereqs.get(codigo) ?? new Set();
    return [...reqs].filter((r) => !completed.has(r));
  };

  const missingCoreqs = (codigo) => {
    const reqs = coreqs.get(codigo) ?? new Set();
    return [...reqs].filter((r) => !completed.has(r) && !selectedSet.has(r));
  };

  const canSelect = (codigo) => {
    if (alreadyPlanned.has(codigo) && !seedCodes.includes(codigo)) {
      return { ok: false, reason: "already planned in another semester" };
    }

    const missPre = missingPrereqs(codigo);
    if (missPre.length > 0) {
      return {
        ok: false,
        reason: `missing prerequisites: ${missPre.join(", ")}`,
      };
    }

    if (strictCoreq) {
      const coReqs = [...(coreqs.get(codigo) ?? [])];
      const anyNotOffered = coReqs.some((r) => {
        if (completed.has(r)) return false;
        // When semOferta is true, offerByCode is empty — check if the co-req exists in the PPC
        if (semOferta) return !nodes.has(r);
        return !offerByCode.has(r);
      });
      if (anyNotOffered) {
        return {
          ok: false,
          reason: "co-requisite not offered this semester",
        };
      }
    }

    const missCo = missingCoreqs(codigo);
    if (missCo.length > 0) {
      return {
        ok: false,
        reason: `missing co-requisites: ${missCo.join(", ")}`,
      };
    }

    return { ok: true, reason: "" };
  };

  const addCourse = (codigo) => {
    selected.push(codigo);
    selectedSet.add(codigo);
  };

  // Seed: keep what was already in the semester, if still valid
  for (const codigo of seedCodes) {
    if (!semOferta && !offerByCode.has(codigo)) continue;
    if (canSelect(codigo).ok) addCourse(codigo);
  }

  // Fixpoint: add new courses while there is progress
  let progressed = true;
  let pass = 0;
  while (progressed && pass < 10) {
    pass++;
    progressed = false;
    for (const codigo of offeredCodes) {
      if (selectedSet.has(codigo)) continue;
      if (!semOferta && !offerByCode.has(codigo)) continue;
      if (alreadyPlanned.has(codigo) && !seedCodes.includes(codigo)) continue;
      if (!canSelect(codigo).ok) continue;
      addCourse(codigo);
      progressed = true;
    }
  }

  // Build the semester rows
  const newRows = selected.map((codigo) => {
    const nodeName = nodes.get(codigo)?.nome ?? "";
    const pre = [...(prereqs.get(codigo) ?? [])].sort();
    const co = [...(coreqs.get(codigo) ?? [])].sort();

    const oferta =
      semOferta || !offerByCode.has(codigo)
        ? { codigo, nome: "", periodo: "", carga_horaria: "", turmas: [] }
        : offerByCode.get(codigo);

    return {
      semestre_curso: String(courseTerm),
      ano: String(ano),
      semestre_oferta: String(offerTerm),
      codigo: oferta.codigo,
      nome: nodeName || oferta.nome || "",
      periodo: oferta.periodo || "",
      carga_horaria: oferta.carga_horaria || "",
      pre_requisitos: pre,
      co_requisitos: co,
      turmas: Array.isArray(oferta.turmas) ? oferta.turmas : [],
    };
  });

  return { newRows, courseTerm, ano, offerTerm };
}

/**
 * Enriches planning rows with turma/horario data from the offer JSONs.
 *
 * For each row with semestre_oferta "1" or "2", looks up the discipline in
 * the corresponding offer and fills the `turmas` field.
 * Rows that already have turmas are left untouched.
 * Rows without semestre_oferta try S1 first, then S2.
 *
 * @param {any[]} rows
 * @param {object} offer1Json
 * @param {object} offer2Json
 * @param {"dia"|"manha"|"tarde"} turno
 * @returns {any[]}
 */
export function enrichRowsWithOffer(
  rows,
  offer1Json,
  offer2Json,
  turno = "dia",
) {
  // filterTurno=true: filters sections by shift when enriching
  const indexS1 = buildOfferIndex(offer1Json ?? {}, turno, true);
  const indexS2 = buildOfferIndex(offer2Json ?? {}, turno, true);

  return (Array.isArray(rows) ? rows : []).map((row) => {
    // Waiver row: skip enrichment
    if (String(row?.semestre_curso ?? "").trim() === "_") return row;

    // If the row already has sections (even without schedules), do not overwrite —
    // existing sections indicate the user has already made choices.
    const existingTurmas = Array.isArray(row?.turmas) ? row.turmas : [];
    if (existingTurmas.length > 0) return row;

    const codigo = String(row?.codigo ?? "").trim();
    if (!codigo) return row;

    const so = String(row?.semestre_oferta ?? "").trim();

    // Determine which offer index(es) to look up
    let ofertaEntry = null;
    if (so === "1") {
      ofertaEntry = indexS1.get(codigo) ?? null;
    } else if (so === "2") {
      ofertaEntry = indexS2.get(codigo) ?? null;
    } else {
      // No semestre_oferta defined: try S1 then S2
      ofertaEntry = indexS1.get(codigo) ?? indexS2.get(codigo) ?? null;
    }

    if (!ofertaEntry || ofertaEntry.turmas.length === 0) return row;

    return {
      ...row,
      // Also update nome/ch/periodo if empty on the row
      nome: row.nome || ofertaEntry.nome || row.nome,
      periodo: row.periodo || ofertaEntry.periodo || row.periodo,
      carga_horaria:
        row.carga_horaria || ofertaEntry.carga_horaria || row.carga_horaria,
      // Include all sections — the user resolves conflicts and chooses later
      turmas: ofertaEntry.turmas,
    };
  });
}

/**
 * Calculates courses available to add to an existing semester.
 *
 * Returns courses from the PPC that:
 * - Have all prerequisites met (prior semesters or waivers)
 * - Are not already planned in any semester
 * - Are not already in the current period (courseTerm)
 *
 * @param {{
 *   rows: any[],
 *   ppcJson: object,
 *   offerJson: object | null,
 *   turno: string,
 *   courseTerm: number,
 *   entryTerm?: number,
 *   anoInicio?: number,
 *   scInicio?: number,
 * }} params
 * @returns {any[]} — PlanningRows ready to add
 */
export function calcAvailableToAdd({
  rows,
  ppcJson,
  offerJson,
  turno,
  courseTerm,
  existingTermCodes = [],
  entryTerm = 1,
  anoInicio = 2024,
  scInicio = 1,
}) {
  const { nodes, prereqs, coreqs, suggestedSemester } =
    buildCourseGraph(ppcJson);

  const offerByCode = offerJson ? buildOfferIndex(offerJson, turno) : new Map();

  const completed = buildCompletedSet(rows, courseTerm);
  const alreadyPlanned = buildAlreadyPlannedSet(rows);

  // Codes already in the current period (passed explicitly by the caller,
  // since rows was filtered without the current period)
  const currentPeriodCodes = new Set(
    (Array.isArray(existingTermCodes) ? existingTermCodes : []).map((c) =>
      String(c ?? "").trim(),
    ),
  );

  const isDisciplinaCodigo = (c) =>
    /^[A-Z]{2,}\d{3,}$/.test(String(c ?? "").trim());

  const disponiveis = [];

  for (const [codigo] of nodes) {
    if (!isDisciplinaCodigo(codigo)) continue;
    if (currentPeriodCodes.has(codigo)) continue; // already in the period
    if (alreadyPlanned.has(codigo)) continue; // already planned in another semester

    // Check prerequisites
    const missPre = [...(prereqs.get(codigo) ?? [])].filter(
      (r) => !completed.has(r),
    );
    if (missPre.length > 0) continue;

    // Check co-requisites — a co-req must be completed or available
    // (no pending prerequisites), same logic as generateSemester with strictCoreq
    const coReqs = [...(coreqs.get(codigo) ?? [])];
    const coReqBloqueado = coReqs.some((r) => {
      if (completed.has(r)) return false; // already completed — ok
      // co-req not completed: check if it itself has pending prerequisites
      const missCoPrereq = [...(prereqs.get(r) ?? [])].filter(
        (p) => !completed.has(p),
      );
      return missCoPrereq.length > 0; // blocked if co-req has a pending prereq
    });
    if (coReqBloqueado) continue;

    const nodeName = nodes.get(codigo)?.nome ?? "";
    const pre = [...(prereqs.get(codigo) ?? [])].sort();
    const co = [...(coreqs.get(codigo) ?? [])].sort();

    const oferta = offerByCode.has(codigo)
      ? offerByCode.get(codigo)
      : { codigo, nome: "", periodo: "", carga_horaria: "", turmas: [] };

    disponiveis.push({
      semestre_curso: String(courseTerm),
      ano: String(anoInicio + Math.floor((courseTerm - scInicio) / 2)),
      semestre_oferta: String(
        ((entryTerm - 1 + (courseTerm - scInicio)) % 2) + 1,
      ),
      codigo: oferta.codigo,
      nome: nodeName || oferta.nome || "",
      periodo: oferta.periodo || "",
      carga_horaria: oferta.carga_horaria || "",
      pre_requisitos: pre,
      co_requisitos: co,
      turmas: Array.isArray(oferta.turmas) ? oferta.turmas : [],
    });
  }

  // Sort by suggested semester in the PPC
  disponiveis.sort((a, b) => {
    const sa = suggestedSemester.get(a.codigo) ?? 9999;
    const sb = suggestedSemester.get(b.codigo) ?? 9999;
    if (sa !== sb) return sa - sb;
    return a.codigo.localeCompare(b.codigo);
  });

  return disponiveis;
}

/**
 * Removes all rows for a given course semester from the planning.
 *
 * @param {any[]} rows
 * @param {number|string} courseTerm
 * @returns {any[]}
 */
export function deleteSemester(rows, courseTerm) {
  const target = String(courseTerm).trim();
  return (Array.isArray(rows) ? rows : []).filter(
    (r) => String(r?.semestre_curso ?? "").trim() !== target,
  );
}

/**
 * Replaces the rows of a course semester with a new set.
 * Sorts by numeric semestre_curso then by code.
 *
 * @param {any[]} rows
 * @param {number} courseTerm
 * @param {any[]} newRows
 * @returns {any[]}
 */
export function upsertSemester(rows, courseTerm, newRows) {
  const keep = (Array.isArray(rows) ? rows : []).filter(
    (r) => Number(r?.semestre_curso) !== courseTerm,
  );
  return [...keep, ...(Array.isArray(newRows) ? newRows : [])].sort((a, b) => {
    const sa = Number(a?.semestre_curso);
    const sb = Number(b?.semestre_curso);
    if (Number.isFinite(sa) && Number.isFinite(sb) && sa !== sb) return sa - sb;
    if (Number.isFinite(sa) && !Number.isFinite(sb)) return -1;
    if (!Number.isFinite(sa) && Number.isFinite(sb)) return 1;
    return String(a?.codigo ?? "").localeCompare(String(b?.codigo ?? ""));
  });
}

/**
 * Ensures uniqueness by (semestre_curso + codigo), merging turmas from duplicates.
 *
 * @param {any[]} rows
 * @returns {any[]}
 */
export function groupUnique(rows) {
  const out = new Map();
  for (const r of Array.isArray(rows) ? rows : []) {
    const sc = String(r?.semestre_curso ?? "").trim();
    const code = String(r?.codigo ?? "").trim();
    if (!code) continue;
    const key = `${sc}::${code}`;
    if (!out.has(key)) {
      out.set(key, r);
      continue;
    }
    const prev = out.get(key);
    out.set(key, {
      ...prev,
      ...r,
      turmas: [
        ...(Array.isArray(prev.turmas) ? prev.turmas : []),
        ...(Array.isArray(r.turmas) ? r.turmas : []),
      ],
    });
  }
  return Array.from(out.values());
}

// ---------------------------------------------------------------------------
// Internal helpers (not exported)
// ---------------------------------------------------------------------------

function buildCompletedSet(rows, targetSc) {
  const completed = new Set();
  for (const r of Array.isArray(rows) ? rows : []) {
    const sc = String(r?.semestre_curso ?? "").trim();
    if (sc === "_") {
      completed.add(r.codigo);
      continue;
    }
    const n = Number(sc);
    if (Number.isFinite(n) && n > 0 && n < targetSc) {
      completed.add(r.codigo);
    }
  }
  return completed;
}

function buildAlreadyPlannedSet(rows) {
  const planned = new Set();
  for (const r of Array.isArray(rows) ? rows : []) planned.add(r.codigo);
  return planned;
}

function rowsForTerm(rows, sc) {
  return (Array.isArray(rows) ? rows : []).filter(
    (r) => Number(r?.semestre_curso) === sc,
  );
}
